# Generated by Django 5.2.7 on 2025-10-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(default='DJ Whizzy', max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('bpm', models.IntegerField()),
                ('duration', models.CharField(default='3:30', max_length=20)),
                ('artwork', models.URLField(blank=True, max_length=500, null=True)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('plays', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
