# Generated by Django 5.2.7 on 2025-10-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('track_plays', models.IntegerField(default=0)),
                ('chat_sessions', models.IntegerField(default=0)),
                ('total_fans', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('merch_views', models.IntegerField(default=0)),
                ('event_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Analytics',
                'ordering': ['-date'],
            },
        ),
    ]
